local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("STREKE HUB", "DarkTheme")
local Tab = Window:NewTab("ادوات عاديه")
local Section = Tab:NewSection("ادوات")
Section:NewButton("ادمن", "ButtonInfo", function()
  loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
    print("Clicked")
end)
Section:NewButton("طيران", "ButtonInfo", function()
  loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Gui-Fly-v3-37111"))()
    print("Clicked")
end)
